name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Debug CI files
      run: ls -R  # ✅ Check if tests exist

    - name: Debug pytest collection
      run: pytest --collect-only  # ✅ Check if pytest finds tests

    - name: Test with pytest
      run: pytest tests/ --verbose  # ✅ Explicitly run tests

